### ISSUE TITLE
Verify the Action in the Marketplace

### ISSUE THREAD

**Issue by dihmandrake** [dependabot/fetch-metadata#117]
Currently this Action in the Marketplace is not verified, which can be confusing and might has an security impact.
Usually all official GitHub Actions in the marketplace are "verified".

I noticed it when moving the "auto-merge" to the suggested procedure the suggested example in the [GitHub Docs](https://cs-workbench.corp.google.com/accounts?a=459937445) and it failed because my security setting for Actions did not allow unverified Actions (found in the repository settings).
While the workaround is straightforward by whitelisting this action, it would be great to have this Action verified in the Marketplace (probably requires some GitHub internal procedures).

Edit:
I think the entire organization _dependabot_ needs to be verified as stated in these links:

- [Publisher Verification](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization)
- [How to become verified creator of a github action?](https://github.community/t/how-to-become-verified-creator-of-a-github-action/116009)

**Comment by brrygrdn** [comment]
The Dependabot organization should now be fully verified, so this issue should be resolved.

**Comment by mkutz** [comment]
Well, in the marketplace dependabot is still not marked as a verified creator (see [fetch-metadata](https://github.com/marketplace/actions/fetch-metadata-from-dependabot-prs). E.g. [slack-send](https://github.com/marketplace/actions/slack-send) is verified.
Maybe another release needs to happen?
